name: Deploy to GitHub Pages

on:
  push:
    branches:
      - host_branch

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Replace API key in JavaScript
        run: sed -i 's/__API_KEY__/${{ secrets.MY_API_KEY }}/g' js/index.j

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: .
